name: Auto PR Drafter

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  handle-new-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is not draft
        id: check_pr_status
        run: |
          if [[ "${{ github.event.pull_request.draft }}" == "false" ]]; then
            echo "is_draft=false" >> $GITHUB_OUTPUT
          else
            echo "is_draft=true" >> $GITHUB_OUTPUT
          fi

      - name: Convert PR to draft
        if: steps.check_pr_status.outputs.is_draft == 'false'
        uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-auto-convert-PR-to-draft.yaml@29-convert-prs-to-draft-after-every-commit-on-an-open-pr
        with:
          pr_number: ${{ github.event.pull_request.number }}
          skip_label_check: false
          comment_on_pr: true
